### ISSUE TITLE
about the up-3d dataset

### ISSUE THREAD

**Issue by ZephirGe** [classner/up#1]
when I use your dataset, I try to project 3D model on the image plane.But some instances are not consistent, such as this(2616)
![test001](https://user-images.githubusercontent.com/22791167/34355415-12eeb8ac-ea70-11e7-937e-aa9e1203a9a6.png)
Are the camera parameters you provided wrong?

**Comment by classner** [comment]
Hi!

Thank you for your interest in the dataset! No, the camera parameters are correct, however for the MPII dataset (from which this is an image), I often used crops around the person to produce the 3D fits. The crop information is stored in files `'%05d_fit_crop_info.txt' % (im_idx)` (for an example on how to set up the camera with it, see, e.g., https://github.com/classner/up/blob/master/pose/tools/create_dataset.py).

Best,
Christoph
