### ISSUE TITLE
DensePose to SMPL

### ISSUE THREAD

**Issue by ingramator** [classner/up#10]
Has anyone here attempted to fit the densepose predictions to this model and produce an animated output?

**Comment by classner** [comment]
Hi @ingramator ! Alp Güler used the UP dataset for some things with his his DenseReg project. However, the idea for the DenseReg and DensePose projects is slightly different in that they care for the visible regions of the body whereas UP predicts all landmark positions.

**Comment by classner** [comment]
There is a way and rewriting the minimization completely is not necessary. Take a look at https://github.com/classner/up/blob/master/3dfit/bodyfit.py#L424; this defines the error objective for the points. You can use a different set of points than the one that is used here by default. However, this may require again careful adaptation of the energy weighting terms.
