### ISSUE TITLE
Some wrong parameters in the dataset?

### ISSUE THREAD

**Issue by ypflll** [classner/up#11]
I try to project the vertexes to 2d using the parameters in .pkl file (02628_body.pkl for example). But I find for some images (especially for images from mpii), the result is wrong:
![image](https://user-images.githubusercontent.com/12528364/46147732-e655cb80-c298-11e8-9053-6718d9a50a98.png)

I use an opencv function to do the projection:
```
m = load_model( 'basicModel_m_lbs_10_207_0_v1.0.0.pkl' )
file_name = b'02628_body.pkl'
f = open(file_name, 'rb')
info = pickle.load(f)
m.pose[:] = info['pose']
m.betas[:] = info['betas']
m.trans[:] = info['trans']

img = cv2.imread('02628_image.png'))
h,w,_ = img.shape
k=np.zeros(5)
c=np.array((w,h)) / 2.
f=(info['f'], info['f'])
camera_mtx = np.array([[f[0], 0, c[0]],[0., f[1], c[1]],[0.,0.,1.]], dtype=np.float64)
point_projected = cv2.projectPoints(m.r, info['rt'], info['t'], camera_mtx, k)
```

I find that 'rt' is always [0., 0., 0.] and 'f' is always 5000.0.
I wonder if the parameters in .pkl file is always right, or you just set them to a fixed value?

**Comment by ypflll** [comment]
@classner I cantacted Federica who sayed he uses opendr to deal with camera. However, I tried opendr (which uses opencv internally) and got the same result. Code:

```
import opendr.camera as _odr_c
camera = _odr_c.ProjectPoints3D(
    rt=info['rt'],
    t=info['t'],
    f=(info['f'], info['f']),
    c=np.array((w,h)) / 2.,
    k=np.zeros(5))
camera.v = np.vstack((m.r))
point_projected = camera.r.T.copy()
```

Cause the rotation vector 'rt' is always [0.,0.,0.], I even write a projection fuction by myself:
```
def project_points_3d(vertex, rt, t, f, c, k=np.zeros(5)):
	## now only support rt=[0.,0.,0.], k=[0.,0.,0.,0.,0.]
	vertex = vertex + t

	X = vertex[:,0]
	Y = vertex[:,1]
	Z = vertex[:,2]

	x = X/Z
	y = Y/Z
	u = f*x + c[0]
	v = f*y + c[1]

	return np.array([u,v])
```

Use this also get the same result.

So I wonder if the parameters in .pkl file is always right.

**Comment by ypflll** [comment]
Figure it out.
Two things I ignore:
1. Crop size must be used to translate and zoom;
2. Use UP provided neutral model instead of SMPL model.

**Comment by Aparajit-Garg** [comment]
Hi @ypflll, glad you figured out the repo. I am getting stuck at the depth estimation module. I have ran the pose/pose.py script  and I am able to plot the keypoints on the image. Now I want to generate the 3d model of the image and plot the keypoints on the image in 3 dimensions. This is the error I'm getting at depth module:
No such file or directory: 'direct3d/../models/2dto3d/separate_regressors/forest_82_final.z'

and another thing is that 2 files are being generated by direct3d/bodyfit.py namely,
1.) 33.png_body_directseparate.pkl_working
2.) work_lock

Upon opening these files the first one has the character 't' in it and the second one is empty.

Can you please explain me what is that I am doing wrong? Or what should I do to resolve my problems here.

Thank you.
