### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by shoukna** [classner/up#14]
Hi, I am training the segmentation with using the test2.caffemodel you provided.

> python segmentation.py xxx.png

But I get the following error, and I use nvidia-smi to see the use of gpu, there is no other process.
How can I solve this problem? Thank you @classner 

`[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 539792218
I0323 19:55:29.644702  6432 net.cpp:816] Ignoring source layer data
I0323 19:55:29.644721  6432 net.cpp:816] Ignoring source layer data_data_0_split
I0323 19:55:29.644728  6432 net.cpp:816] Ignoring source layer label_data_1_split
I0323 19:55:29.744916  6432 net.cpp:816] Ignoring source layer fc1_training_c0
I0323 19:55:29.744940  6432 net.cpp:816] Ignoring source layer fc1_training_c1
I0323 19:55:29.744959  6432 net.cpp:816] Ignoring source layer fc1_training_c2
I0323 19:55:29.744977  6432 net.cpp:816] Ignoring source layer fc1_training_c3
I0323 19:55:29.744983  6432 net.cpp:816] Ignoring source layer fc1_training
I0323 19:55:29.744987  6432 net.cpp:816] Ignoring source layer fc1_training_fc1_training_0_split
I0323 19:55:29.744998  6432 net.cpp:816] Ignoring source layer fc1_training_res05_c0
I0323 19:55:29.745005  6432 net.cpp:816] Ignoring source layer fc1_training_res05_c1
I0323 19:55:29.745010  6432 net.cpp:816] Ignoring source layer fc1_training_res05_c2
I0323 19:55:29.745018  6432 net.cpp:816] Ignoring source layer fc1_training_res05_c3
I0323 19:55:29.745023  6432 net.cpp:816] Ignoring source layer fc1_training_res05
I0323 19:55:29.745028  6432 net.cpp:816] Ignoring source layer fc1_training_res05_fc1_training_res05_0_split
I0323 19:55:29.745036  6432 net.cpp:816] Ignoring source layer fc1_training_res075_c0
I0323 19:55:29.745043  6432 net.cpp:816] Ignoring source layer fc1_training_res075_c1
I0323 19:55:29.745048  6432 net.cpp:816] Ignoring source layer fc1_training_res075_c2
I0323 19:55:29.745054  6432 net.cpp:816] Ignoring source layer fc1_training_res075_c3
I0323 19:55:29.745060  6432 net.cpp:816] Ignoring source layer fc1_training_res075
I0323 19:55:29.745066  6432 net.cpp:816] Ignoring source layer fc1_training_res05_interp
I0323 19:55:29.745074  6432 net.cpp:816] Ignoring source layer fc1_training_res075_interp
I0323 19:55:29.745077  6432 net.cpp:816] Ignoring source layer fc1_training_res075_interp_fc1_training_res075_interp_0_split
I0323 19:55:29.745086  6432 net.cpp:816] Ignoring source layer fc_fusion_fc_fusion_0_split
I0323 19:55:29.745095  6432 net.cpp:816] Ignoring source layer label_shrink
I0323 19:55:29.745100  6432 net.cpp:816] Ignoring source layer label_shrink_label_shrink_0_split
I0323 19:55:29.745105  6432 net.cpp:816] Ignoring source layer loss
I0323 19:55:29.745110  6432 net.cpp:816] Ignoring source layer accuracy
I0323 19:55:29.745115  6432 net.cpp:816] Ignoring source layer loss_res1
I0323 19:55:29.745121  6432 net.cpp:816] Ignoring source layer accuracy_res1
I0323 19:55:29.745126  6432 net.cpp:816] Ignoring source layer loss_res075
I0323 19:55:29.745129  6432 net.cpp:816] Ignoring source layer accuracy_res075
I0323 19:55:29.745136  6432 net.cpp:816] Ignoring source layer label_shrink16
I0323 19:55:29.745141  6432 net.cpp:816] Ignoring source layer label_shrink16_label_shrink16_0_split
I0323 19:55:29.745146  6432 net.cpp:816] Ignoring source layer loss_res05
I0323 19:55:29.745152  6432 net.cpp:816] Ignoring source layer accuracy_res05
INFO:__main__:Done!
F0323 19:55:30.254861  6432 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)
`

**Comment by classner** [comment]
Hi @shoukna ,

this probably means that the model does not fit on the GPU you're using. You can try:
* to use a GPU with more memory,
* to reduce the batch size, if possible,
* to run on the CPU,
* to use an entirely different model core.

Running on the CPU will be very slow. You can also try to use a more memory-saving model core, such as a smaller resnet.

**Comment by shoukna** [comment]
Hi @classner ,
when I use the CPU to create a model,
```
./run.sh train mymodelname
```
the following error appears:
```
I0324 19:09:41.832707 22904 net.cpp:283] Network initialization done.
I0324 19:09:41.835124 22904 solver.cpp:60] Solver scaffolding done.
I0324 19:09:41.836936 22904 caffe.cpp:129] Finetuning from training/config/seg_2/init.caffemodel
I0324 19:09:41.920564 22904 net.cpp:816] Ignoring source layer fc1_coco
I0324 19:09:41.920596 22904 net.cpp:816] Ignoring source layer fc1_coco_fc1_coco_0_split
I0324 19:09:41.921278 22904 caffe.cpp:219] Starting Optimization
I0324 19:09:41.921288 22904 solver.cpp:280] Solving seg_2
I0324 19:09:41.921293 22904 solver.cpp:281] Learning Rate Policy: poly
F0324 19:09:42.016870 22904 blob.cpp:163] Check failed: data_
*** Check failure stack trace: ***
    @     0x7f99a3ca888d  google::LogMessage::Fail()
    @     0x7f99a3caae43  google::LogMessage::SendToLog()
    @     0x7f99a3ca837b  google::LogMessage::Flush()
    @     0x7f99a3ca9d8e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f99a408049b  caffe::Blob<>::mutable_cpu_data()
    @     0x7f99a421b027  caffe::BatchNormLayer<>::Forward_cpu()
    @     0x7f99a40998d3  caffe::Net<>::ForwardFromTo()
    @     0x7f99a4099b47  caffe::Net<>::ForwardPrefilled()
    @     0x7f99a407acb5  caffe::Solver<>::Step()
    @     0x7f99a407b729  caffe::Solver<>::Solve()
    @           0x40adeb  train()
    @           0x407188  main
    @     0x7f99a2964830  __libc_start_main
    @           0x4078e9  _start
./run.sh: line 78: 22904 Aborted                 (core dumped) ${CMD}
```

**Comment by classner** [comment]
Hi @shoukna,
Hmmm, that looks like a problem with caffe. Unfortunately, I am not working with caffe any more and can not support you with debugging through this. I can only recommend further searching for the issue or debugging (with, for example, gdb) what is going on in detail. Sorry to not be able to help you out in more detail! If everything else fails, you can also try to re-build the model in one of the major deep learning frameworks. It should be relatively straightforward; the main contribution for this project was rather on the data and pipelining side than the model side and you can still make use of the resulting dataset.

Best,
Christoph

**Comment by shoukna** [comment]
Thank you so mush @classner

**Comment by wojiaolyj** [comment]
I have a problem with insufficient memory with 12g gpu. I want to know how much memory is needed to execute this file.   thanks@classner 
    python segmentation.py xxx.png

**Comment by classner** [comment]
Hi @wojiaolyj ,

there is no need for a larger GPU, I was using a 12 Gb GPU myself to execute the models. I could only imagine that the batch size plays a role here.

Best,
Christoph
