### ISSUE TITLE
meshio for i/o

### ISSUE THREAD

**Issue by nschloe** [classner/up#18]
I recently updated [meshio](https://github.com/nschloe/meshio) to include support for PLY, and using it as a drop-in replacement for plyfile would increase the number of supported mesh formats by a great deal. Perhaps that's worth considering.

**Comment by classner** [comment]
Hi @nschloe !

This sounds great, thanks for the pointer! Would you be willing to create a PR with the replacement?

**Comment by nschloe** [comment]
See https://github.com/classner/up/pull/19.

**Comment by classner** [comment]
Thanks again! :)
