### ISSUE TITLE
Would you like to provide the crop & scale information in your UP-91 dataset

### ISSUE THREAD

**Issue by kennymckormick** [classner/up#2]
Hi, Classner. Recently I'm working on something about dense landmarks on human body. I found the UP-91 dataset you provided really fasinating. But I meet some problems when I want to intergrate your 91p landmark with the original 14p-h label. Would you please provide some information about how you crop and scale images from these original dataset? Thank you very much!

**Comment by classner** [comment]
Hi @kennymckormick!

Glad you like the dataset and sorry for the delayed response! The crop information is available for all images in the corresponding `'%05d_fit_crop_info.txt' % (im_idx)` files. You can find an example on how to use the crop information [here](https://github.com/classner/up/blob/master/pose/tools/create_dataset.py#L110).

Best,
Christoph
