### ISSUE TITLE
One image is taking Average 5mins for processing bodyfit.

### ISSUE THREAD

**Issue by Vamshigoud784** [classner/up#20]
One image is taking Average 5mins for processing bodyfit . is there any way can i optimize and reduce the time. i have built the gpu docker but it still takes the sometime. any help?

thanks,
Vamshi

**Comment by classner** [comment]
Not really in this setting, especially the detailed model takes a while to fit. The direct prediction code is certainly a lot faster, but with worse quality. If you care mostly about the 3D fits from segmentation, also check out https://github.com/mohomran/neural_body_fitting . If you're caring about 3D body estimation from pictures in general, there are also other newer repositories that attempt to solve the general problem in a direct prediction way.
