### ISSUE TITLE
Where can I find the code of silhouette fitting

### ISSUE THREAD

**Issue by dbgns** [classner/up#21]
Thanks for your nice work! As you mentioned, the sihouette fitting code is not released due to license reason, then where can I find this code? Thanks a lot!

**Comment by classner** [comment]
Sorry, it is not published and you'd have to implement it yourself.

**Comment by dbgns** [comment]
Alright, thank you!

**Comment by foermozhu** [comment]
> Alright, thank you!

Hi,do you find the sihouette fitting code,I'm also studying this part.
Look forward to your reply，thanks！！
如果可以的话我们可以交流一下吗？

**Comment by dbgns** [comment]
> > Alright, thank you!
> 
> Hi,do you find the sihouette fitting code,I'm also studying this part.
> Look forward to your reply，thanks！！
> 如果可以的话我们可以交流一下吗？

Hi! There are some possible solutions: 
* You may implement the silhouette fitting by yourself, and you can refer to chamfer loss in [pytorch3d](https://pytorch3d.org). 
* You may refer to [nips17](https://github.com/htung0101/3d_smpl), which also uses silhouette as a supervision signal(they implement by distance maps), but our experiments show that such supervision is quite coarse and fragile, (do not recommend)
* Do not use the silhouette as the supervison, use differentiable rendering instead. You can refer to [Softras](https://github.com/ShichenLiu/SoftRas) and [Neural Mesh Renderer](https://github.com/daniilidis-group/neural_renderer) for more details. The idea is to use mask(gt or by segmentation model) to supervise the shape of humans. But on datasets that only have a limited number of subjects(e.g. Human3.6M), such practice may not work. 

Good luck!
