### ISSUE TITLE
Meshio assertion error

### ISSUE THREAD

**Issue by minar09** [classner/up#22]
I am getting error while running 3dfit/render.py, meshio cannot read .ply format file

AssertionError: Could not deduce file format from extension '. ../up/3dfit/../models/3D/template.ply'.

**Comment by classner** [comment]
Hi @minar09 ,

The change to meshio was done in https://github.com/classner/up/pull/19 . Maybe @nschloe can say something on this? The meshio website explicitly mentions compatibility with .ply, so I'm not sure what's causing this.

**Comment by minar09** [comment]
Hi @classner , I am getting this error in python 2.7 version (linux).
For now, I reverted back to old commit before meshio, plyfile is working fine.

**Comment by nschloe** [comment]
meshio supports all Python versions that are supported by upstream, i.e., 3.5+ as of now.
