### ISSUE TITLE
Mismatch between original image and the rendered 3D human model

### ISSUE THREAD

**Issue by krumo** [classner/up#23]
Hi,

I am trying to render projected 3D human model on the original image using [3dfit/render.py](https://github.com/classner/up/blob/master/3dfit/render.py). Although it works for some examples, it would produce mismatched results on some examples as following:
![index](https://user-images.githubusercontent.com/9900913/82215254-6837b400-9917-11ea-9321-785c402fb459.png)
Could you help me to solve this problem? Thanks in advance!
Plus, in case you want to reproduce the results by yourselve, the example image in this issue is `05122_image.png`.

**Comment by classner** [comment]
Hi @krumo,

Glad you find this code useful! You seem to be using un-cropped images, for which the code is not suitable. You'd have to re-map the rendering from the cropped to the uncropped version. Unfortunately, I do not have time to give you detailed guidance on this at the moment.

**Comment by Aparajit-Garg** [comment]
Hi @krumo, amazing you were able to reproduce the code. I'm actually getting stuck in the depth estimation model as it's not there with me.

No such file or directory: 'direct3d/../models/2dto3d/separate_regressors/forest_82_final.z'

and another thing is that 2 files are being generated namely,
1.) 33.png_body_directseparate.pkl_working
2.) work_lock

Upon opening these files the first one has the character 't' in it and the second one is empty.
My end goal is to generate the 3d model for the image and map points on the 3d model. Can you please help me out, how you did it?
