### ISSUE TITLE
Aligning images, parts and keypoints

### ISSUE THREAD

**Issue by Ushk** [classner/up#24]
It'd be very useful to be able to align the semantic part labels, keypoints and 3d images - I've been trying to figure out how to do this, but can't seem to find instructions or reverse engineer the cropping pipeline. Are there instructions that I've missed, or could you offer any advice?

I've looked at the `{}_fit_crop_info.txt` files, but these seem to give a crop of a different size. I've looked at `person_size = robust_person_size(joints)` and `norm_factor = float(target_person_size) / person_size` as well, but the function signature for the first doesn't seem to match the function definition (expects pose as a first parameter? Judging by the shape this is not the pose from the pickle file?) and I'm not 100% sure what the value for target_person_size should be (looks like 500?)

**Comment by Ushk** [comment]
![image](https://user-images.githubusercontent.com/15078052/91351227-daa21500-e7df-11ea-9c02-255fb6d5ab3a.png)
![image](https://user-images.githubusercontent.com/15078052/91351243-dfff5f80-e7df-11ea-8394-768ceb76abab.png)

- got it!

```
crop_y, crop_x = get_crop(image, person_center, 513)
```

should be 
```
crop_y, crop_x = get_crop(image, norm_factor*person_center, 513)
```

**Comment by classner** [comment]
Hi @Ushk ,

Sorry for my slow reply, glad you figured it out! :) Good luck with your project!
