### ISSUE TITLE
Index in the SMPL model and vertices?

### ISSUE THREAD

**Issue by wangzheallen** [classner/up#25]
https://github.com/classner/up/blob/4c376f639b08bc3bd2e5df23037f99a0b63f27f8/up_tools/model.py#L345 has the landmarks.pkl pickle file to read, however, I did not find the pickle location in the model webpage?

May I ask whether the 91 joints are all from SMPL model? if so, may I have the indexes for the vertices?

**Comment by classner** [comment]
Hi @wangzheallen !

The .pkl files are part of the download packages! The 91 vertices are part of the SMPL model, though not all 'joints'. Some of them are the skeleton joints, others are vertices on the body surface. There is an index structure in this repo here: https://github.com/classner/up/blob/d55fd57571899a9e8a2af04cba22b9111a6b68ea/up_tools/model.py#L349 .

**Comment by wangzheallen** [comment]
Hi @classner ！

Thanks for the kind reply! I just downloaed checked again with SMPL folder, all up-3d downloaded files, and SMPlify folder, however, I did not find the landmarks.pkl. Could you help specify where to download the pkl file?

**Comment by classner** [comment]
Oh, now I know what you mean! You should not have to search for this at all if you follow the installation instructions, it's part of this software package and you can find it here: https://github.com/classner/up/tree/master/models/pose .

**Comment by wangzheallen** [comment]
I see! thanks very much for pointing this out! :-)
