### ISSUE TITLE
How to transform mpii 2d keypoint to correspond to image?

### ISSUE THREAD

**Issue by ky66111** [classner/up#27]
![image](https://user-images.githubusercontent.com/16101166/110808354-ddb5ac00-82be-11eb-943c-767096b1f294.png)
Seems like provided mpii 2d keypoint in `poses.npz` locates as relative position to left upper corner of bounding box, and scaling by a scalar. 
As shown in figure below row2(original) vs row3(manually multiply a scalar). 
![image](https://user-images.githubusercontent.com/16101166/110811820-02f7e980-82c2-11eb-9cf9-103aef266521.png)
I wonder how to calculate this scaling scalar? It's changed depend to each sample.

**Comment by classner** [comment]
Hi @ky66111!

Yes, the crops must be mapped back into the images. You can find all details in the dataset preparation script here: https://github.com/classner/up/blob/master/segmentation/tools/create_dataset.py . All the required data to run it is available in the dataset package files.
