### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by zhangzhenyu-zzy** [classner/up#28]
hello,i want to use this dataset ,is there any way can make me get the human mask?i know the dataset has the segmentation image,like this
![5MM E$5%_}TJ`)}N@U3VQXV](https://user-images.githubusercontent.com/81757380/133887779-f041c9d2-9eaa-4540-9357-e393a5014811.png)

but i just want get the mask of the people in this image,like the people in white color,and the background in black coclor
can you help me?

**Comment by classner** [comment]
Hi @zhangzhenyu-zzy ,

The image on the left is only a visualization of the segmentation mask. You can find the mask itself also as part of the dataset. It contains per pixel a value starting from 0 (background) up for each segment. You can just use all pixels with a value >0 to get the foreground mask.

Hope that helps and good luck with your project!
Christoph

**Comment by zhangzhenyu-zzy** [comment]
thank you very much!, I get it succesful
![53QNSXKHCJDY53 Y$F7B86V](https://user-images.githubusercontent.com/81757380/134100041-3dca99fd-3624-4a5a-b32d-d5b4ba36bc33.png)
